#
# Wizard autogenerated makefile.
# DO NOT EDIT, use the oxidane_user.mk file instead.
#

# Constants automatically defined by the selected modules
oxidane_DEBUG = 1

# Our target application
TRG += oxidane

oxidane_PREFIX = "/usr/local/toolchain/gcc-arm-none-eabi-7-2018-q2-update/bin/arm-none-eabi-"

oxidane_SUFFIX = ""

oxidane_SRC_PATH = oxidane

oxidane_HW_PATH = oxidane

# Files automatically generated by the wizard. DO NOT EDIT, USE oxidane_USER_CSRC INSTEAD!
oxidane_WIZARD_CSRC = \
	bertos/cfg/kfile_debug.c \
	bertos/cpu/cortex-m3/drv/i2c_stm32.c \
	bertos/cpu/cortex-m3/drv/spi_stm32.c \
	bertos/cpu/cortex-m3/drv/timer_cm3.c \
	bertos/drv/i2c.c \
	bertos/drv/i2c_bitbang.c \
	bertos/drv/ow_1wire.c \
	bertos/drv/spi_bitbang.c \
	bertos/drv/timer.c \
	bertos/io/kfile.c \
	bertos/mware/event.c \
	bertos/mware/formatwr.c \
	bertos/mware/hex.c \
	#

# Files automatically generated by the wizard. DO NOT EDIT, USE oxidane_USER_PCSRC INSTEAD!
oxidane_WIZARD_PCSRC = \
	 \
	#

# Files automatically generated by the wizard. DO NOT EDIT, USE oxidane_USER_CPPASRC INSTEAD!
oxidane_WIZARD_CPPASRC = \
	 \
	#

# Files automatically generated by the wizard. DO NOT EDIT, USE oxidane_USER_CXXSRC INSTEAD!
oxidane_WIZARD_CXXSRC = \
	 \
	#

# Files automatically generated by the wizard. DO NOT EDIT, USE oxidane_USER_ASRC INSTEAD!
oxidane_WIZARD_ASRC = \
	 \
	#

oxidane_CPPFLAGS = -D'CPU_FREQ=(32000000UL)' -D'ARCH=(ARCH_DEFAULT)' -D'WIZ_AUTOGEN' -I$(oxidane_HW_PATH) -I$(oxidane_SRC_PATH) $(oxidane_CPU_CPPFLAGS) $(oxidane_USER_CPPFLAGS)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
oxidane_LDFLAGS = $(oxidane_CPU_LDFLAGS) $(oxidane_WIZARD_LDFLAGS) $(oxidane_USER_LDFLAGS)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
oxidane_CPPAFLAGS = $(oxidane_CPU_CPPAFLAGS) $(oxidane_WIZARD_CPPAFLAGS) $(oxidane_USER_CPPAFLAGS)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
oxidane_CSRC = $(oxidane_CPU_CSRC) $(oxidane_WIZARD_CSRC) $(oxidane_USER_CSRC)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
oxidane_PCSRC = $(oxidane_CPU_PCSRC) $(oxidane_WIZARD_PCSRC) $(oxidane_USER_PCSRC)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
oxidane_CPPASRC = $(oxidane_CPU_CPPASRC) $(oxidane_WIZARD_CPPASRC) $(oxidane_USER_CPPASRC)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
oxidane_CXXSRC = $(oxidane_CPU_CXXSRC) $(oxidane_WIZARD_CXXSRC) $(oxidane_USER_CXXSRC)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
oxidane_ASRC = $(oxidane_CPU_ASRC) $(oxidane_WIZARD_ASRC) $(oxidane_USER_ASRC)

# CPU specific flags and options, defined in the CPU definition files.
# Automatically generated by the wizard. PLEASE DO NOT EDIT!
oxidane_CPU_CPPASRC = bertos/cpu/cortex-m3/hw/crt_cm3.S bertos/cpu/cortex-m3/hw/vectors_cm3.S 
oxidane_CPU_CPPAFLAGS = -g -gdwarf-2 -mthumb -mno-thumb-interwork
oxidane_CPU_CPPFLAGS = -O0 -g3 -gdwarf-2 -mthumb -mno-thumb-interwork -fno-strict-aliasing -fwrapv -fverbose-asm -Ibertos/cpu/cortex-m3/ -D__ARM_STM32L152RE__
oxidane_CPU_CSRC = bertos/cpu/cortex-m3/hw/init_cm3.c bertos/cpu/cortex-m3/drv/irq_cm3.c bertos/cpu/cortex-m3/drv/gpio_stm32.c bertos/cpu/cortex-m3/drv/clock_stm32.c 
oxidane_PROGRAMMER_CPU = stm32
oxidane_CPU_LDFLAGS = -mthumb -mno-thumb-interwork -nostartfiles -Wl,--no-warn-mismatch -Wl,-dT bertos/cpu/cortex-m3/scripts/stm32l152re_rom.ld
oxidane_STOPFLASH_SCRIPT = bertos/prg_scripts/arm/stopopenocd.sh
oxidane_CPU = cortex-m3
oxidane_STOPDEBUG_SCRIPT = bertos/prg_scripts/arm/stopopenocd.sh
oxidane_DEBUG_SCRIPT = bertos/prg_scripts/arm/debug.sh
oxidane_FLASH_SCRIPT = bertos/prg_scripts/arm/flash-stm32.sh

include $(oxidane_SRC_PATH)/oxidane_user.mk
