#!/bin/bash

# script/server
# Flash the firmware on the board and run it

set -eu

cd "$(dirname "$0")/.."

if [ $# -lt 1 ]; then
	echo "Usage: script/server SERIAL"
	exit 1
fi

# Build the project first
./script/build

# Produce the output .bin file to be flashed
output="$(mktemp)"
arm-none-eabi-objcopy -O binary target/thumbv7m-none-eabi/debug/oxidane "$output"

# Flash the .bin file
stm32flash -w "$output" -v -g 0x0 -b 115200 -R -i -rts,dtr,-dtr:rts,dtr,-dtr $1

# Remove output file
rm "$output"

