#!/bin/sh

# scripts/setup
# Perform the required one-time setup of the project, including bootstrapping

set -eu

cd "$(dirname "$0")/.."

# Dependency bootstrapping
./script/bootstrap

# Build project
cargo +nightly build

