#!/bin/bash

# script/bootstrap
# Resolve all the dependencies required by the application to run.

set -eu

cd "$(dirname "$0")/.."

# Check if a specific program is already installed and available
check_installed()
{
	[ -n "$(command -v $1)" ] && return 0 || return 1
}

# Docker as build environment
if ! check_installed docker; then
	echo "Docker missing!"
	exit 1
fi

# STM32 loader
if ! check_installed stm32flash; then
	echo "STM32 flash tool missing!"
	exit 1
fi

